steps:
  - task: DotNetCoreCLI@2
    displayName: 'Build the project - Release'
    inputs:
      command: 'build'
      arguments: '--no-restore --configuration Release'
      projects: '**/*.csproj'

  - task: DotNetCoreCLI@2
    displayName: 'Run unit tests - Release'
    inputs:
      command: 'test'
      arguments: '--no-build --configuration Release'
      publishTestResults: true
      projects: '**/*.Tests.csproj'

  - task: DotNetCoreCLI@2
    displayName: 'Publish the project - Release'
    inputs:
      command: 'publish'
      projects: '$(System.DefaultWorkingDirectory)/**/Tailspin.SpaceGame.Web.csproj'
      publishWebProjects: false
      arguments: '--no-build --configuration Release --output $(Build.ArtifactStagingDirectory)'
      zipAfterPublish: true