parameters:
  - name: deploymentName
    type: string
  
  - name: environment
    type: string

  - name: appName
    type: string

  - name: webAppName
    type: string

jobs:
  - deployment: ${{ parameters.deploymentName }}
    pool:
      vmImage: 'ubuntu-20.04'
    environment: ${{ parameters.environment }}
    variables:
      - group: 'Release'
    strategy:
      runOnce:
        deploy:
          steps:
            - download: current
              artifact: drop
            - task: AzureWebApp@1
              displayName: 'Azure App Service Deploy: website'
              inputs:
                azureSubscription: 'Resource Manager - Tailspin - Space Game'
                appName: ${{ parameters.webAppName }}
                package: '$(Pipeline.Workspace)/drop/${{ parameters.appName }}.zip'
