parameters:
  - name: dependsOn
    type: string
    default: 'DeployTest'
  
  - name: dotnetSdkVersion
    type: string

jobs:
  - job: RunUITests
    dependsOn: ${{ parameters.dependsOn }}
    displayName: 'Run UI tests'
    condition: false
    pool:
      vmImage: 'windows-2019'
    variables:
      - group: 'Release'
    steps:
      - task: UseDotNet@2
        displayName: 'Use .NET SDK ${{ parameters.dotnetSdkVersion }}'
        inputs:
          packageType: sdk
          version: ${{ parameters.dotnetSdkVersion }}

      - task: DotNetCoreCLI@2
        displayName: 'Build the project - ${{ parameters.dotnetSdkVersion }}'
        inputs:
          command: 'build'
          arguments: '--configuration Release'
          projects: '$(System.DefaultWorkingDirectory)/**/Tailspin.SpaceGame.Web.UITests.csproj'

      - task: DotNetCoreCLI@2
        displayName: 'Run UI tests - Release'
        inputs:
          command: 'test'
          arguments: '--no-build --configuration Release'
          publishTestResults: true
          projects: '$(System.DefaultWorkingDirectory)/**/Tailspin.SpaceGame.Web.UITests.csproj'
        timeoutInMinutes: 2
